# ~/.config/starship.toml

add_newline = false

[cmd_duration]
min_time = 10000

[directory]
truncation_length = 3
prefix = ""

[aws]
symbol = "[aws] "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = "[conda] "

[git_branch]
symbol = "[git] "

[golang]
symbol = "[go] "

[hg_branch]
symbol = "[hg] "

[java]
symbol = "[java] "

[memory_usage]
disabled = true

[nodejs]
symbol = "⬢ "

[package]
symbol = "[pkg] "

[php]
symbol = "[php] "

[python]
symbol = "[py] "

[ruby]
symbol = "[rb] "

[rust]
symbol = "[rust] "
