#! /bin/sh
#
# ==================================================================
# Copyright (C) %YEAR% %USER% <%MAIL%>
# Distributed under terms of the %LICENSE% license.
#
# @author: %USER%
# @github: %MAIL%
# @created: %DATE%
# ==================================================================

all:
	%HERE%@echo "%FFILE% needs your attention"


# vim:ft=make
